[Thread-9] WEBORB ERROR:23/4/2010 08:50:26:Db4objects.Db4o.Ext.DatabaseFileLockedException: C:\dev\sistemadaempresa\ambiente_desenvolvimento\marcos\banco_de_dados\Banco\0.dbf ---> System.IO.IOException: The process cannot access the file 'C:\dev\sistemadaempresa\ambiente_desenvolvimento\marcos\banco_de_dados\Banco\0.dbf' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Sharpen.IO.RandomAccessFile..ctor(String file, Boolean readOnly, Boolean lockFile)
   at Db4objects.Db4o.IO.RandomAccessFileFactory.NewRandomAccessFile(String path, Boolean readOnly, Boolean lockFile)
   --- End of inner exception stack trace ---
   at Db4objects.Db4o.IO.RandomAccessFileFactory.NewRandomAccessFile(String path, Boolean readOnly, Boolean lockFile)
   at Db4objects.Db4o.IO.FileStorage.FileBin..ctor(BinConfiguration config)
   at Db4objects.Db4o.IO.FileStorage.Open(BinConfiguration config)
   at Db4objects.Db4o.IO.StorageDecorator.Open(BinConfiguration config)
   at Db4objects.Db4o.IO.CachingStorage.Open(BinConfiguration config)
   at Db4objects.Db4o.Internal.IoAdaptedObjectContainer.OpenImpl()
   at Db4objects.Db4o.Internal.ObjectContainerBase._IRunnable_104.Run()
   at Db4objects.Db4o.Foundation.DynamicVariable.With(Object value, IRunnable block)
   at Db4objects.Db4o.Foundation.Environments.RunWith(IEnvironment environment, IRunnable runnable)
   at Db4objects.Db4o.Internal.ObjectContainerBase.WithEnvironment(IRunnable runnable)
   at Db4objects.Db4o.Internal.ObjectContainerBase.Open()
   at Db4objects.Db4o.Internal.IoAdaptedObjectContainer..ctor(IConfiguration config, String fileName)
   at Db4objects.Db4o.Internal.ObjectContainerFactory.OpenObjectContainer(IConfiguration config, String databaseFileName)
   at Db4objects.Db4o.Db4oFactory.OpenFile(IConfiguration config, String databaseFileName)
   at Db4objects.Db4o.Db4oFactory.OpenFile(String databaseFileName)
   at GerenteConectividadeBancoDados.get(Int32 idCorp, TipoBanco tipoBanco) in C:\dev\sistemadaempresa\ambiente_desenvolvimento\marcos\lado_servidor\sde_marcos\SDE\code\pattern\GerenteConectividadeBancoDados.cs:line 99
   at SDE.CamadaServico.SuperServico..ctor() in C:\dev\sistemadaempresa\ambiente_desenvolvimento\marcos\lado_servidor\sde_marcos\SDE\code\CamadaServico\SuperServico.cs:line 14
   at SDE.CamadaServico.SLogin..ctor()
[Thread-9] WEBORB ERROR:23/4/2010 08:50:55:Db4objects.Db4o.Ext.DatabaseFileLockedException: C:\dev\sistemadaempresa\ambiente_desenvolvimento\marcos\banco_de_dados\Banco\0.dbf ---> System.IO.IOException: The process cannot access the file 'C:\dev\sistemadaempresa\ambiente_desenvolvimento\marcos\banco_de_dados\Banco\0.dbf' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Sharpen.IO.RandomAccessFile..ctor(String file, Boolean readOnly, Boolean lockFile)
   at Db4objects.Db4o.IO.RandomAccessFileFactory.NewRandomAccessFile(String path, Boolean readOnly, Boolean lockFile)
   --- End of inner exception stack trace ---
   at Db4objects.Db4o.IO.RandomAccessFileFactory.NewRandomAccessFile(String path, Boolean readOnly, Boolean lockFile)
   at Db4objects.Db4o.IO.FileStorage.FileBin..ctor(BinConfiguration config)
   at Db4objects.Db4o.IO.FileStorage.Open(BinConfiguration config)
   at Db4objects.Db4o.IO.StorageDecorator.Open(BinConfiguration config)
   at Db4objects.Db4o.IO.CachingStorage.Open(BinConfiguration config)
   at Db4objects.Db4o.Internal.IoAdaptedObjectContainer.OpenImpl()
   at Db4objects.Db4o.Internal.ObjectContainerBase._IRunnable_104.Run()
   at Db4objects.Db4o.Foundation.DynamicVariable.With(Object value, IRunnable block)
   at Db4objects.Db4o.Foundation.Environments.RunWith(IEnvironment environment, IRunnable runnable)
   at Db4objects.Db4o.Internal.ObjectContainerBase.WithEnvironment(IRunnable runnable)
   at Db4objects.Db4o.Internal.ObjectContainerBase.Open()
   at Db4objects.Db4o.Internal.IoAdaptedObjectContainer..ctor(IConfiguration config, String fileName)
   at Db4objects.Db4o.Internal.ObjectContainerFactory.OpenObjectContainer(IConfiguration config, String databaseFileName)
   at Db4objects.Db4o.Db4oFactory.OpenFile(IConfiguration config, String databaseFileName)
   at Db4objects.Db4o.Db4oFactory.OpenFile(String databaseFileName)
   at GerenteConectividadeBancoDados.get(Int32 idCorp, TipoBanco tipoBanco) in C:\dev\sistemadaempresa\ambiente_desenvolvimento\marcos\lado_servidor\sde_marcos\SDE\code\pattern\GerenteConectividadeBancoDados.cs:line 99
   at SDE.CamadaServico.SuperServico..ctor() in C:\dev\sistemadaempresa\ambiente_desenvolvimento\marcos\lado_servidor\sde_marcos\SDE\code\CamadaServico\SuperServico.cs:line 14
   at SDE.CamadaServico.SLogin..ctor()
[Thread-9] WEBORB ERROR:23/4/2010 08:51:12:Db4objects.Db4o.Ext.DatabaseFileLockedException: C:\dev\sistemadaempresa\ambiente_desenvolvimento\marcos\banco_de_dados\Banco\0.dbf ---> System.IO.IOException: The process cannot access the file 'C:\dev\sistemadaempresa\ambiente_desenvolvimento\marcos\banco_de_dados\Banco\0.dbf' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Sharpen.IO.RandomAccessFile..ctor(String file, Boolean readOnly, Boolean lockFile)
   at Db4objects.Db4o.IO.RandomAccessFileFactory.NewRandomAccessFile(String path, Boolean readOnly, Boolean lockFile)
   --- End of inner exception stack trace ---
   at Db4objects.Db4o.IO.RandomAccessFileFactory.NewRandomAccessFile(String path, Boolean readOnly, Boolean lockFile)
   at Db4objects.Db4o.IO.FileStorage.FileBin..ctor(BinConfiguration config)
   at Db4objects.Db4o.IO.FileStorage.Open(BinConfiguration config)
   at Db4objects.Db4o.IO.StorageDecorator.Open(BinConfiguration config)
   at Db4objects.Db4o.IO.CachingStorage.Open(BinConfiguration config)
   at Db4objects.Db4o.Internal.IoAdaptedObjectContainer.OpenImpl()
   at Db4objects.Db4o.Internal.ObjectContainerBase._IRunnable_104.Run()
   at Db4objects.Db4o.Foundation.DynamicVariable.With(Object value, IRunnable block)
   at Db4objects.Db4o.Foundation.Environments.RunWith(IEnvironment environment, IRunnable runnable)
   at Db4objects.Db4o.Internal.ObjectContainerBase.WithEnvironment(IRunnable runnable)
   at Db4objects.Db4o.Internal.ObjectContainerBase.Open()
   at Db4objects.Db4o.Internal.IoAdaptedObjectContainer..ctor(IConfiguration config, String fileName)
   at Db4objects.Db4o.Internal.ObjectContainerFactory.OpenObjectContainer(IConfiguration config, String databaseFileName)
   at Db4objects.Db4o.Db4oFactory.OpenFile(IConfiguration config, String databaseFileName)
   at Db4objects.Db4o.Db4oFactory.OpenFile(String databaseFileName)
   at GerenteConectividadeBancoDados.get(Int32 idCorp, TipoBanco tipoBanco) in C:\dev\sistemadaempresa\ambiente_desenvolvimento\marcos\lado_servidor\sde_marcos\SDE\code\pattern\GerenteConectividadeBancoDados.cs:line 99
   at SDE.CamadaServico.SuperServico..ctor() in C:\dev\sistemadaempresa\ambiente_desenvolvimento\marcos\lado_servidor\sde_marcos\SDE\code\CamadaServico\SuperServico.cs:line 14
   at SDE.CamadaServico.SLogin..ctor()
[Thread-9] WEBORB ERROR:23/4/2010 08:51:13:Db4objects.Db4o.Ext.DatabaseFileLockedException: C:\dev\sistemadaempresa\ambiente_desenvolvimento\marcos\banco_de_dados\Banco\0.dbf ---> System.IO.IOException: The process cannot access the file 'C:\dev\sistemadaempresa\ambiente_desenvolvimento\marcos\banco_de_dados\Banco\0.dbf' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Sharpen.IO.RandomAccessFile..ctor(String file, Boolean readOnly, Boolean lockFile)
   at Db4objects.Db4o.IO.RandomAccessFileFactory.NewRandomAccessFile(String path, Boolean readOnly, Boolean lockFile)
   --- End of inner exception stack trace ---
   at Db4objects.Db4o.IO.RandomAccessFileFactory.NewRandomAccessFile(String path, Boolean readOnly, Boolean lockFile)
   at Db4objects.Db4o.IO.FileStorage.FileBin..ctor(BinConfiguration config)
   at Db4objects.Db4o.IO.FileStorage.Open(BinConfiguration config)
   at Db4objects.Db4o.IO.StorageDecorator.Open(BinConfiguration config)
   at Db4objects.Db4o.IO.CachingStorage.Open(BinConfiguration config)
   at Db4objects.Db4o.Internal.IoAdaptedObjectContainer.OpenImpl()
   at Db4objects.Db4o.Internal.ObjectContainerBase._IRunnable_104.Run()
   at Db4objects.Db4o.Foundation.DynamicVariable.With(Object value, IRunnable block)
   at Db4objects.Db4o.Foundation.Environments.RunWith(IEnvironment environment, IRunnable runnable)
   at Db4objects.Db4o.Internal.ObjectContainerBase.WithEnvironment(IRunnable runnable)
   at Db4objects.Db4o.Internal.ObjectContainerBase.Open()
   at Db4objects.Db4o.Internal.IoAdaptedObjectContainer..ctor(IConfiguration config, String fileName)
   at Db4objects.Db4o.Internal.ObjectContainerFactory.OpenObjectContainer(IConfiguration config, String databaseFileName)
   at Db4objects.Db4o.Db4oFactory.OpenFile(IConfiguration config, String databaseFileName)
   at Db4objects.Db4o.Db4oFactory.OpenFile(String databaseFileName)
   at GerenteConectividadeBancoDados.get(Int32 idCorp, TipoBanco tipoBanco) in C:\dev\sistemadaempresa\ambiente_desenvolvimento\marcos\lado_servidor\sde_marcos\SDE\code\pattern\GerenteConectividadeBancoDados.cs:line 99
   at SDE.CamadaServico.SuperServico..ctor() in C:\dev\sistemadaempresa\ambiente_desenvolvimento\marcos\lado_servidor\sde_marcos\SDE\code\CamadaServico\SuperServico.cs:line 14
   at SDE.CamadaServico.SLogin..ctor()
[Thread-4] WEBORB ERROR:23/4/2010 09:15:30:Db4objects.Db4o.Ext.DatabaseFileLockedException: C:\dev\sistemadaempresa\ambiente_desenvolvimento\marcos\banco_de_dados\Banco\0.dbf ---> System.IO.IOException: The process cannot access the file 'C:\dev\sistemadaempresa\ambiente_desenvolvimento\marcos\banco_de_dados\Banco\0.dbf' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Sharpen.IO.RandomAccessFile..ctor(String file, Boolean readOnly, Boolean lockFile)
   at Db4objects.Db4o.IO.RandomAccessFileFactory.NewRandomAccessFile(String path, Boolean readOnly, Boolean lockFile)
   --- End of inner exception stack trace ---
   at Db4objects.Db4o.IO.RandomAccessFileFactory.NewRandomAccessFile(String path, Boolean readOnly, Boolean lockFile)
   at Db4objects.Db4o.IO.FileStorage.FileBin..ctor(BinConfiguration config)
   at Db4objects.Db4o.IO.FileStorage.Open(BinConfiguration config)
   at Db4objects.Db4o.IO.StorageDecorator.Open(BinConfiguration config)
   at Db4objects.Db4o.IO.CachingStorage.Open(BinConfiguration config)
   at Db4objects.Db4o.Internal.IoAdaptedObjectContainer.OpenImpl()
   at Db4objects.Db4o.Internal.ObjectContainerBase._IRunnable_104.Run()
   at Db4objects.Db4o.Foundation.DynamicVariable.With(Object value, IRunnable block)
   at Db4objects.Db4o.Foundation.Environments.RunWith(IEnvironment environment, IRunnable runnable)
   at Db4objects.Db4o.Internal.ObjectContainerBase.WithEnvironment(IRunnable runnable)
   at Db4objects.Db4o.Internal.ObjectContainerBase.Open()
   at Db4objects.Db4o.Internal.IoAdaptedObjectContainer..ctor(IConfiguration config, String fileName)
   at Db4objects.Db4o.Internal.ObjectContainerFactory.OpenObjectContainer(IConfiguration config, String databaseFileName)
   at Db4objects.Db4o.Db4oFactory.OpenFile(IConfiguration config, String databaseFileName)
   at Db4objects.Db4o.Db4oFactory.OpenFile(String databaseFileName)
   at GerenteConectividadeBancoDados.get(Int32 idCorp, TipoBanco tipoBanco) in C:\dev\sistemadaempresa\ambiente_desenvolvimento\marcos\lado_servidor\sde_marcos\SDE\code\pattern\GerenteConectividadeBancoDados.cs:line 99
   at SDE.CamadaServico.SuperServico..ctor() in C:\dev\sistemadaempresa\ambiente_desenvolvimento\marcos\lado_servidor\sde_marcos\SDE\code\CamadaServico\SuperServico.cs:line 14
   at SDE.CamadaServico.SLogin..ctor()
[Thread-4] WEBORB ERROR:23/4/2010 17:07:53:System.Exception: [erro anotado 56] Object reference not set to an instance of an object.    at SDE.CamadaNuvem.NuvemModificacoes.CargoPermissoes_NovosAtualiza(Int32 idCorp, List`1 objetos) in C:\dev\sistemadaempresa\ambiente_desenvolvimento\marcos\lado_servidor\sde_marcos\SDE\code\CamadaNuvem\NuvemModificacoes_Cliente.cs:line 209 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at SDE.CamadaNuvem.NuvemModificacoes.CargoPermissoes_NovosAtualiza(Int32 idCorp, List`1 objetos) in C:\dev\sistemadaempresa\ambiente_desenvolvimento\marcos\lado_servidor\sde_marcos\SDE\code\CamadaNuvem\NuvemModificacoes_Cliente.cs:line 209
   --- End of inner exception stack trace ---
   at SDE.CamadaNuvem.SuperNuvem.dbRollback(Exception ex, IObjectContainer[] dbList) in C:\dev\sistemadaempresa\ambiente_desenvolvimento\marcos\lado_servidor\sde_marcos\SDE\code\CamadaNuvem\SuperNuvem.cs:line 65
   at SDE.CamadaNuvem.NuvemModificacoes.CargoPermissoes_NovosAtualiza(Int32 idCorp, List`1 objetos) in C:\dev\sistemadaempresa\ambiente_desenvolvimento\marcos\lado_servidor\sde_marcos\SDE\code\CamadaNuvem\NuvemModificacoes_Cliente.cs:line 232
